feat: Add a game menu to replay the game
CleanCut/invaders pull request #4
Opened 2021-06-16 20:20 UTC by sp-luciano-chinke

Hi!

After finishing your Ultimate Rust Crash Course in Udemy, you encouraged me into trying to do something new in Rust (thanks! ^^). I'm still a begginer, but I would love to have Rust as my main language in the future.

I decided to try to create a system to manage a game menu where the user can choose to start a new game or end it. I also made some tweaks trying things and probably left a couple of comments like 'How can I improve this?' as a self reminder.

Hope you like it ^^!

2021-06-18 16:55 UTC, CleanCut commented
Cool! I tried it out real quick just to make sure it works. I'm heads-down working on Rusty Engine to get it ready for [a live-session I'm doing on O'Reilly next Tuesday](https://agileperception.com/), so I've put this on my list to do a thorough code review later on next week.

In the meantime, feel free to continue refining it and pushing new commits up to this branch if you like. 😄

2021-06-24 17:55 UTC, CleanCut commented
@sp-luciano-chinke I'm ready! Before I can give this a proper review, it needs the changes in master merged in and resolved.  I've actually _already done that_, but I don't have permissions to push the change to your fork.

Can you check the `[ ] Allow edits by maintainers` checkbox on this pull request so I can push that up?

<img width="549" alt="image" src="https://user-images.githubusercontent.com/5838512/123310086-f438e980-d4e2-11eb-89e7-99b5658588ce.png">

2021-06-24 20:06 UTC, CleanCut commented on .gitignore
> +.DS_Store
I don't mind adding this, but you should also add this pattern to your own [global .gitignore file](https://gist.github.com/subfuzion/db7f57fff2fb6998a16c) -- otherwise you will have to deal with this for every project you ever contribute to, and some will be unwilling to accept the pattern. (I [learned](https://github.com/CleanCut/dotfiles/blob/main/homefiles/.gitignore-global) that the hard way 😉)

2021-06-25 12:13 UTC, sp-luciano-chinke commented
@CleanCut Done! Sorry for the inconveniences, it's my first time contributing in an open source project. Thanks for the advice, I've already set it up for future cases. Nice tip! :)

2021-06-25 19:36 UTC, CleanCut requested changes
This is a great start!  I think we can make it even better, and you may learn some useful things along the way! 😄 Before you start making changes, remember to do `git pull` to get the commit I pushed up!

As I look through your pull request, I see that it is more complicated than it needs to be, so let's go through a couple steps to simplify things!

First, let's simplify the code by removing everything about `Scenes` and using a `bool` in `main()` instead.  Something like `let mut in_menu = false;`, for example.  There are only two states: in the menu, or not in the menu. So we don't need more than a boolean.

As you make changes to other code that touched `Scenes`, see if you can do any of the following:
- Simplify code
- Fix bugs (did you notice you can select a blank menu item below "Exit"?)
- Decouple your code. For example, `Player` probably shouldn't need to know anything about the menu.

When you've done what you can, push up your changes and let's take another look and see what the next step is! This is fun!

2021-06-25 19:36 UTC, CleanCut commented on src/main.rs
> +    }
Let's move this outside of the `main()` function.  It's not idiomatic to define a function within a function, unless you're treating it like a closure and passing it as an argument to something else.

2021-06-25 19:36 UTC, CleanCut commented on src/main.rs
> +    }
I think this function is more confusing than it's worth. I suggest doing the loop in-place for the place that has multiple things to draw, and in the menu place just do: `menu.draw(&mut curr_frame)` rather than putting a single item into a vector just to send it to a function to iterate over one item to do the same call.

2021-06-25 19:36 UTC, CleanCut commented on src/main.rs
> +    }
We can simplify!

```suggestion
    for sound in ["explode", "lose", "move", "pew", "startup", "win"] {
        audio.add(sound, &format!("{}.wav", sound));
    }
```

2021-06-25 19:36 UTC, CleanCut commented on src/lib.rs
> +pub enum Scenes {
(We're removing this, but...)
* if we were to keep this, it should be moved to a submodule.
* if we were to keep this, the name of an `enum` should correspond to what _a variant is_. For example, if you said "what is a `Game`?" You would answer "it is a `Scene`."

```suggestion
pub enum Scene {
```

2021-06-25 19:36 UTC, CleanCut commented on src/main.rs
>  use std::{io, thread};
I should have cleaned up these `use` statements long ago. Would you like to do that for me? This is optional, I will accept the pull request without this cleanup if you do not wish to do it.

If you do want to try doing the cleanup, here are some examples on how to combine `use` statements:

```rust
// These two lines...
use std::sync::mpsc;
use std::sync::mpsc::Receiver;

// would become this (`self` brings `mpsc` into scope)
use std::sync::mpsc::{self, Receiver};
```

Another example: 
```rust
// These lines...
use crossterm::cursor::{Hide, Show};
use crossterm::terminal::{EnterAlternateScreen, LeaveAlternateScreen};
use crossterm::{terminal, ExecutableCommand};

// would become
use crossterm::{
    cursor::{Hide, Show},
    terminal::{self, EnterAlternateScreen, LeaveAlternateScreen},
    ExecutableCommand,
};
```

2021-06-25 19:36 UTC, CleanCut commented on src/main.rs
> +            // How can I improve this? (used to avoid problems with references)
If we kept this code, the answer would be to stop using references!  You should avoid using references with `Copy` types whenever possible.

2021-06-28 19:34 UTC, sp-luciano-chinke commented
Hi @CleanCut ! 

Thanks all the feedback given here, really appreciated. I applied all the suggested changes and improved the `use` statements, hope you like them ^^! I was really trying to have the input handlers attached to Player or the Menu, but I couldn't find an easy way to do it. Do you have any thoughts on that? 🤔

2021-07-02 16:36 UTC, CleanCut reviewed
We're just about there! If you could make the slight changes I indicated in this latest review, I'll go ahead and merge.

2021-07-02 16:36 UTC, CleanCut commented on src/main.rs
> +                            in_menu = true;
`reset_game(...)` on the next line already does this.

```suggestion
```

2021-07-02 16:36 UTC, CleanCut commented on src/main.rs
> +        } else {
If we finish the rendering logic and add a `continue` here, then we can get rid of the whole `else` block, decrease the indent level for all the rest of the main game loop, and not worry about whether we are in a menu later on.

```suggestion
            let _ = render_tx.send(curr_frame);
            thread::sleep(Duration::from_millis(1));
            continue;
        }
```

2021-07-02 16:36 UTC, CleanCut commented on src/main.rs
> +        if !in_menu {
```suggestion
```

With my earlier suggestion of adding a `continue` in the menu handling, we will no longer reach this code while in a menu.

2021-07-06 22:29 UTC, sp-luciano-chinke commented
Hi @CleanCut ! Already applied the gameloop fixes. Thanks for pointing them out! ^^

2021-07-08 04:24 UTC, CleanCut approved these changes

2021-07-08 04:40 UTC, merged